<?php
/******************************************************
******************* Advanced Custom Fields ************
******************************************************/
include_once( ABSPATH . 'wp-admin/includes/plugin.php' );


if( ! is_plugin_active( 'advanced-custom-fields-pro/acf.php' ) ) {

  // Customize ACF path
  add_filter('acf/settings/path', 'tw_acf_settings_path');
  function tw_acf_settings_path( $path ) {
    $path = get_template_directory() . '/plugins/advanced-custom-fields-pro/';
    return $path;
  }

  // Customize ACF dir
  add_filter('acf/settings/dir', 'tw_acf_settings_dir');
  function tw_acf_settings_dir( $dir ) {
    $dir = get_template_directory_uri() . '/plugins/advanced-custom-fields-pro/';
    return $dir;
  }

  // Hide ACF field group menu item
  //add_filter('acf/settings/show_admin', '__return_false');

  // Include ACF
  include_once( get_template_directory() . '/plugins/advanced-custom-fields-pro/acf.php' );
}


// Include ACF Font Awesome Field
/*
if(!function_exists('register_fields_font_awesome')){
  include_once( get_template_directory() . '/plugins/advanced-custom-fields-font-awesome/acf-font-awesome.php' );
}
*/


if( function_exists('acf_add_options_page') ) {

	acf_add_options_page(array(
		'page_title' 	=> 'Theme General Settings',
		'menu_title'	=> 'TW Theme Settings',
		'menu_slug' 	=> 'tw-general-settings',
		'capability'	=> 'edit_posts',
		'redirect'		=> false
	));

	acf_add_options_sub_page(array(
		'page_title' 	=> 'Logos & Icons',
		'menu_title'	=> 'Logos & Icons',
		'parent_slug'	=> 'tw-general-settings',
	));

	acf_add_options_sub_page(array(
		'page_title' 	=> 'Blog Options',
		'menu_title'	=> 'Blog Options',
		'parent_slug'	=> 'tw-general-settings',
	));

	acf_add_options_sub_page(array(
		'page_title' 	=> 'Contact Information',
		'menu_title'	=> 'Contact Information',
		'parent_slug'	=> 'tw-general-settings',
	));

	acf_add_options_sub_page(array(
		'page_title' 	=> 'Social Information',
		'menu_title'	=> 'Social Information',
		'parent_slug'	=> 'tw-general-settings',
	));

	acf_add_options_sub_page(array(
		'page_title' 	=> 'Advanced',
		'menu_title'	=> 'Advanced',
		'parent_slug'	=> 'tw-general-settings',
	));

}

if( function_exists('acf_add_local_field_group') ):

$countries_array = array (
				'Afghanistan' => 'Afghanistan',
				'Albania' => 'Albania',
				'Algeria' => 'Algeria',
				'American Samoa' => 'American Samoa',
				'Andorra' => 'Andorra',
				'Angola' => 'Angola',
				'Antigua and Barbuda' => 'Antigua and Barbuda',
				'Argentina' => 'Argentina',
				'Armenia' => 'Armenia',
				'Australia' => 'Australia',
				'Austria' => 'Austria',
				'Azerbaijan' => 'Azerbaijan',
				'Bahamas' => 'Bahamas',
				'Bahrain' => 'Bahrain',
				'Bangladesh' => 'Bangladesh',
				'Barbados' => 'Barbados',
				'Belarus' => 'Belarus',
				'Belgium' => 'Belgium',
				'Belize' => 'Belize',
				'Benin' => 'Benin',
				'Bermuda' => 'Bermuda',
				'Bhutan' => 'Bhutan',
				'Bolivia' => 'Bolivia',
				'Bosnia and Herzegovina' => 'Bosnia and Herzegovina',
				'Botswana' => 'Botswana',
				'Brazil' => 'Brazil',
				'Brunei' => 'Brunei',
				'Bulgaria' => 'Bulgaria',
				'Burkina Faso' => 'Burkina Faso',
				'Burundi' => 'Burundi',
				'Cambodia' => 'Cambodia',
				'Cameroon' => 'Cameroon',
				'Canada' => 'Canada',
				'Cape Verde' => 'Cape Verde',
				'Cayman Islands' => 'Cayman Islands',
				'Central African Republic' => 'Central African Republic',
				'Chad' => 'Chad',
				'Chile' => 'Chile',
				'China' => 'China',
				'Colombia' => 'Colombia',
				'Comoros' => 'Comoros',
				'Congo, Democratic Republic of the' => 'Congo, Democratic Republic of the',
				'Congo, Republic of the' => 'Congo, Republic of the',
				'Costa Rica' => 'Costa Rica',
				"Côte d'Ivoire" => "Côte d'Ivoire",
				'Croatia' => 'Croatia',
				'Cuba' => 'Cuba',
				'Cyprus' => 'Cyprus',
				'Czech Republic' => 'Czech Republic',
				'Denmark' => 'Denmark',
				'Djibouti' => 'Djibouti',
				'Dominica' => 'Dominica',
				'Dominican Republic' => 'Dominican Republic',
				'East Timor' => 'East Timor',
				'Ecuador' => 'Ecuador',
				'Egypt' => 'Egypt',
				'El Salvador' => 'El Salvador',
				'Equatorial Guinea' => 'Equatorial Guinea',
				'Eritrea' => 'Eritrea',
				'Estonia' => 'Estonia',
				'Ethiopia' => 'Ethiopia',
				'Faroe Islands' => 'Faroe Islands',
				'Fiji' => 'Fiji',
				'Finland' => 'Finland',
				'France' => 'France',
				'French Polynesia' => 'French Polynesia',
				'Gabon' => 'Gabon',
				'Gambia' => 'Gambia',
				'Georgia' => 'Georgia',
				'Germany' => 'Germany',
				'Ghana' => 'Ghana',
				'Greece' => 'Greece',
				'Greenland' => 'Greenland',
				'Grenada' => 'Grenada',
				'Guam' => 'Guam',
				'Guatemala' => 'Guatemala',
				'Guinea' => 'Guinea',
				'Guinea-Bissau' => 'Guinea-Bissau',
				'Guyana' => 'Guyana',
				'Haiti' => 'Haiti',
				'Honduras' => 'Honduras',
				'Hong Kong' => 'Hong Kong',
				'Hungary' => 'Hungary',
				'Iceland' => 'Iceland',
				'India' => 'India',
				'Indonesia' => 'Indonesia',
				'Iran' => 'Iran',
				'Iraq' => 'Iraq',
				'Ireland' => 'Ireland',
				'Israel' => 'Israel',
				'Italy' => 'Italy',
				'Jamaica' => 'Jamaica',
				'Japan' => 'Japan',
				'Jordan' => 'Jordan',
				'Kazakhstan' => 'Kazakhstan',
				'Kenya' => 'Kenya',
				'Kiribati' => 'Kiribati',
				'North Korea' => 'North Korea',
				'South Korea' => 'South Korea',
				'Kosovo' => 'Kosovo',
				'Kuwait' => 'Kuwait',
				'Kyrgyzstan' => 'Kyrgyzstan',
				'Laos' => 'Laos',
				'Latvia' => 'Latvia',
				'Lebanon' => 'Lebanon',
				'Lesotho' => 'Lesotho',
				'Liberia' => 'Liberia',
				'Libya' => 'Libya',
				'Liechtenstein' => 'Liechtenstein',
				'Lithuania' => 'Lithuania',
				'Luxembourg' => 'Luxembourg',
				'Macedonia' => 'Macedonia',
				'Madagascar' => 'Madagascar',
				'Malawi' => 'Malawi',
				'Malaysia' => 'Malaysia',
				'Maldives' => 'Maldives',
				'Mali' => 'Mali',
				'Malta' => 'Malta',
				'Marshall Islands' => 'Marshall Islands',
				'Mauritania' => 'Mauritania',
				'Mauritius' => 'Mauritius',
				'Mexico' => 'Mexico',
				'Micronesia' => 'Micronesia',
				'Moldova' => 'Moldova',
				'Monaco' => 'Monaco',
				'Mongolia' => 'Mongolia',
				'Montenegro' => 'Montenegro',
				'Morocco' => 'Morocco',
				'Mozambique' => 'Mozambique',
				'Myanmar' => 'Myanmar',
				'Namibia' => 'Namibia',
				'Nauru' => 'Nauru',
				'Nepal' => 'Nepal',
				'Netherlands' => 'Netherlands',
				'New Zealand' => 'New Zealand',
				'Nicaragua' => 'Nicaragua',
				'Niger' => 'Niger',
				'Nigeria' => 'Nigeria',
				'Northern Mariana Islands' => 'Northern Mariana Islands',
				'Norway' => 'Norway',
				'Oman' => 'Oman',
				'Pakistan' => 'Pakistan',
				'Palau' => 'Palau',
				'Palestine, State of' => 'Palestine, State of',
				'Panama' => 'Panama',
				'Papua New Guinea' => 'Papua New Guinea',
				'Paraguay' => 'Paraguay',
				'Peru' => 'Peru',
				'Philippines' => 'Philippines',
				'Poland' => 'Poland',
				'Portugal' => 'Portugal',
				'Puerto Rico' => 'Puerto Rico',
				'Qatar' => 'Qatar',
				'Romania' => 'Romania',
				'Russia' => 'Russia',
				'Rwanda' => 'Rwanda',
				'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
				'Saint Lucia' => 'Saint Lucia',
				'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
				'Samoa' => 'Samoa',
				'San Marino' => 'San Marino',
				'Sao Tome and Principe' => 'Sao Tome and Principe',
				'Saudi Arabia' => 'Saudi Arabia',
				'Senegal' => 'Senegal',
				'Serbia' => 'Serbia',
				'Seychelles' => 'Seychelles',
				'Sierra Leone' => 'Sierra Leone',
				'Singapore' => 'Singapore',
				'Sint Maarten' => 'Sint Maarten',
				'Slovakia' => 'Slovakia',
				'Slovenia' => 'Slovenia',
				'Solomon Islands' => 'Solomon Islands',
				'Somalia' => 'Somalia',
				'South Africa' => 'South Africa',
				'Spain' => 'Spain',
				'Sri Lanka' => 'Sri Lanka',
				'Sudan' => 'Sudan',
				'Sudan, South' => 'Sudan, South',
				'Suriname' => 'Suriname',
				'Swaziland' => 'Swaziland',
				'Sweden' => 'Sweden',
				'Switzerland' => 'Switzerland',
				'Syria' => 'Syria',
				'Taiwan' => 'Taiwan',
				'Tajikistan' => 'Tajikistan',
				'Tanzania' => 'Tanzania',
				'Thailand' => 'Thailand',
				'Togo' => 'Togo',
				'Tonga' => 'Tonga',
				'Trinidad and Tobago' => 'Trinidad and Tobago',
				'Tunisia' => 'Tunisia',
				'Turkey' => 'Turkey',
				'Turkmenistan' => 'Turkmenistan',
				'Tuvalu' => 'Tuvalu',
				'Uganda' => 'Uganda',
				'Ukraine' => 'Ukraine',
				'United Arab Emirates' => 'United Arab Emirates',
				'United Kingdom' => 'United Kingdom',
				'United States' => 'United States',
				'Uruguay' => 'Uruguay',
				'Uzbekistan' => 'Uzbekistan',
				'Vanuatu' => 'Vanuatu',
				'Vatican City' => 'Vatican City',
				'Venezuela' => 'Venezuela',
				'Vietnam' => 'Vietnam',
				'Virgin Islands, British' => 'Virgin Islands, British',
				'Virgin Islands, U.S.' => 'Virgin Islands, U.S.',
				'Yemen' => 'Yemen',
				'Zambia' => 'Zambia',
				'Zimbabwe' => 'Zimbabwe',
			);

/****************************************************************
************** General Options **********************************
****************************************************************/
acf_add_local_field_group(array (
	'key' => 'tw_theme_general_options',
	'title' => 'General Options',
	'fields' => array (
		array (
			'key' => 'field_56807961fa5a6',
			'label' => 'Homepage Widgets',
			'name' => 'tw_enable_homepage_widgets',
			'type' => 'true_false',
			'instructions' => 'Add a special widget area for the Homepage Template',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Homepage Widgets',
			'default_value' => 1,
		),
		array (
			'key' => 'field_56807a69d9794',
			'label' => 'Primary Sidebar',
			'name' => 'tw_enable_primary_sidebar',
			'type' => 'true_false',
			'instructions' => 'Enable the default sidewise primary sidebar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Primary Sidebar',
			'default_value' => 1,
		),
		array (
			'key' => 'field_568079d256f5b',
			'label' => 'Slider Transition',
			'name' => 'tw_slider_transition',
			'type' => 'radio',
			'instructions' => 'Select the default carousel transition style',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'slide' => 'Slide',
				'fade' => 'Fade',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'slide',
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'tw-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'tw_theme_mobile_menu_options',
	'title' => 'Mobile Menu Options',
	'fields' => array (
		array (
			'key' => 'field_56967edc2e7d4',
			'label' => 'Mobile Menu Search',
			'name' => 'tw_enable_mobile_menu_search',
			'type' => 'true_false',
			'instructions' => __('This will add a search button next to the mobile menu "hamburger" button. Please note that in smaller sized mobile devices, this might cause issues if the logo is too big.','tw'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Mobile Menu Search',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'tw-general-settings',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Theme Mobile Menu Options',
));


acf_add_local_field_group(array (
	'key' => 'tw_theme_footer_options',
	'title' => 'Footer Options',
	'fields' => array (
		array (
			'key' => 'field_568075d14eb3e',
			'label' => 'Widget Areas',
			'name' => 'tw_footer_widget_areas',
			'type' => 'select',
			'instructions' => 'Select the number of widget areas in the footer',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				0 => 'No Widgets Areas',
				2 => '2 Widget Areas',
				3 => '3 Widget Areas',
				4 => '4 Widget Areas',
			),
			'default_value' => array (
				3 => 3,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_568078a822e6c',
			'label' => 'Menu',
			'name' => 'tw_enable_footer_menu',
			'type' => 'true_false',
			'instructions' => 'Add a menu item to footer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Footer Menu',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5680756f8cda2',
			'label' => 'Social Icons',
			'name' => 'tw_enable_footer_social_icons',
			'type' => 'true_false',
			'instructions' => 'Show the social icons in the footer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Social Icons in Footer',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5680764e72b24',
			'label' => 'Copyright',
			'name' => 'tw_footer_copyright',
			'type' => 'text',
			'instructions' => 'The site copyright text is shown in the absolute bottom of the footer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '© '.date('Y').' '.get_bloginfo('name').' All Rights Reserved',
			'placeholder' => '© '.date('Y').' '.get_bloginfo('name').' All Rights Reserved',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568076cd72b25',
			'label' => 'Credit',
			'name' => 'tw_footer_credit',
			'type' => 'textarea',
			'instructions' => 'Enter the footer developer or design credit text. The site credit text is shown in the absolute bottom of the footer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Designed & Developed by <a href="http://www.thirdwunder.com" target="_blank" title="Third Wunder | Marketing What Matters">Third Wunder</a>',
			'placeholder' => '',
			'maxlength' => 100,
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'tw-general-settings',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));



if ( is_plugin_active( 'gravityforms/gravityforms.php' ) ) {
$forms_array = array(''=>'');
$forms = RGFormsModel::get_forms( null, 'title' );
foreach( $forms as $form ){
  if($form->id!==''){
    $forms_array[$form->id] = $form->title;
  }
}
acf_add_local_field_group(array (
	'key' => 'tw_theme_gravity_forms_options',
	'title' => 'Gravity Form Options',
	'fields' => array (
		array (
			'key' => 'field_568451e580a0b',
			'label' => 'Newsletter Form',
			'name' => 'tw_gf_newsletter_form',
			'type' => 'select',
			'instructions' => 'Choose your Newsletter Gravity Form',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => $forms_array,
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5696886024582',
			'label' => 'Newsletter Form in Footer',
			'name' => 'tw_gf_newsletter_form_in_footer',
			'type' => 'true_false',
			'instructions' => 'Add a newsletter form in the footer.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_568451e580a0b',
						'operator' => '!=',
						'value' => '',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Newsletter Form in the Footer',
			'default_value' => 1,
		),
		array (
			'key' => 'field_5684524f80a0c',
			'label' => 'Contact Form',
			'name' => 'tw_gf_contact_form',
			'type' => 'select',
			'instructions' => 'Select the general contact Gravity Form for use in the Contact Page template.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => $forms_array,
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'tw-general-settings',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Gravity Form Options',
));
}

/****************************************************************
************** Blog Options *************************************
****************************************************************/
acf_add_local_field_group(array (
	'key' => 'tw_theme_post_formats',
	'title' => 'Post Formats',
	'fields' => array (
		array (
			'key' => 'field_56806eee3080d',
			'label' => 'Gallery',
			'name' => 'tw_blog_gallery',
			'type' => 'true_false',
			'instructions' => 'The Gallery post format allows you to add a gallery of images to your post.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable the Gallery post format',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56806f153080e',
			'label' => 'Video',
			'name' => 'tw_blog_video',
			'type' => 'true_false',
			'instructions' => 'The Video post format allows you to add a featured video to your post.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable the Video post format',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56806f2f3080f',
			'label' => 'Audio',
			'name' => 'tw_blog_audio',
			'type' => 'true_false',
			'instructions' => 'The Audio post format allows you to add a featured audio to your post. e.g.: Podcast or audio interview',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable the Audio post format',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5680705446909',
			'label' => 'Quote',
			'name' => 'tw_blog_quote',
			'type' => 'true_false',
			'instructions' => 'The Quote post format allows you to add a featured quote to your post with extra options for author and source details',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable the Quote post format',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5680708d4690a',
			'label' => 'Link',
			'name' => 'tw_blog_link',
			'type' => 'true_false',
			'instructions' => 'The Link post format is a special type of post that links out to its source by default.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable the Link post format',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-blog-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Blog Post Format Options',
));


acf_add_local_field_group(array (
	'key' => 'tw_theme_blog_archive_options',
	'title' => 'Blog Archive Options',
	'fields' => array (
		array (
			'key' => 'field_56842252db6a4',
			'label' => 'Sidebar',
			'name' => 'tw_enable_blog_archive_sidebar',
			'type' => 'true_false',
			'instructions' => 'Add a widget sidebar to the blog archives.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Sidebar',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-blog-options',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));



acf_add_local_field_group(array (
	'key' => 'tw_theme_blog_single_options',
	'title' => 'Blog Single Options',
	'fields' => array (
		array (
			'key' => 'field_568071ea04330',
			'label' => 'Sidebar',
			'name' => 'tw_enable_blog_sidebar',
			'type' => 'true_false',
			'instructions' => 'Add a widget sidebar to the single blog post.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Sidebar',
			'default_value' => 1,
		),
		array (
			'key' => 'field_5680721a04331',
			'label' => 'Related Posts',
			'name' => 'tw_blog_related_posts',
			'type' => 'true_false',
			'instructions' => 'Add a related posts to the single blog post.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable related posts',
			'default_value' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-blog-options',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'tw_theme_blog_category_options',
	'title' => 'Category Options',
	'fields' => array (
		array (
			'key' => 'field_56809cff66005',
			'label' => 'Category Colour',
			'name' => 'tw_enable_category_colour',
			'type' => 'true_false',
			'instructions' => 'Add a colour option to a blog post category',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Category Colour',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56809d4066006',
			'label' => 'Category Image',
			'name' => 'tw_enable_category_image',
			'type' => 'true_false',
			'instructions' => 'Add an image option to a blog post category',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Category Image',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-blog-options',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));


/****************************************************************
************** Logos & Icons ************************************
****************************************************************/
acf_add_local_field_group(array (
	'key' => 'tw_theme_site_logos',
	'title' => 'Site Logos',
	'fields' => array (
		array (
			'key' => 'field_568073763efde',
			'label' => 'Site Logo',
			'name' => 'tw_site_logo',
			'type' => 'image',
			'instructions' => 'Primary site logo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5680739e3efdf',
			'label' => 'Site Logo Alternative',
			'name' => 'tw_site_logo_alt',
			'type' => 'image',
			'instructions' => 'An alternate or inverted logo image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_568073c53efe0',
			'label' => 'Favicon',
			'name' => 'tw_site_favicon',
			'type' => 'image',
			'instructions' => 'A png or ico favicon image. 16x16px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => 16,
			'min_height' => 16,
			'min_size' => '',
			'max_width' => 16,
			'max_height' => 16,
			'max_size' => '',
			'mime_types' => 'png, ico',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-logos-icons',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'tw_theme_apple_bookmark_icons',
	'title' => 'Apple Bookmark Icons',
	'fields' => array (
		array (
			'key' => 'field_5680744b1fffd',
			'label' => 'iPhone 3',
			'name' => 'tw_icon_iphone_3',
			'type' => 'image',
			'instructions' => 'Best results with a square png with max 54x54px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => 54,
			'max_height' => 54,
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5680748c7cb8c',
			'label' => 'iPhone 4',
			'name' => 'tw_icon_iphone_4',
			'type' => 'image',
			'instructions' => 'Best results with a square png with max 72x72px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => 54,
			'min_height' => 54,
			'min_size' => '',
			'max_width' => 72,
			'max_height' => 72,
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_568074a77cb8d',
			'label' => 'iPhone Retina',
			'name' => 'tw_icon_iphone_retina',
			'type' => 'image',
			'instructions' => 'Best results with a square png with max 114x114px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => 72,
			'min_height' => 72,
			'min_size' => '',
			'max_width' => 114,
			'max_height' => 114,
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_568074db7cb8e',
			'label' => 'iPad',
			'name' => 'tw_icon_ipad',
			'type' => 'image',
			'instructions' => 'Best results with a square png with max 144x144px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => 114,
			'min_height' => 114,
			'min_size' => '',
			'max_width' => 144,
			'max_height' => 144,
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-logos-icons',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Apple Bookmark Icons',
));


/****************************************************************
************** Contact Details **********************************
****************************************************************/
acf_add_local_field_group(array (
	'key' => 'tw_theme_contact_details',
	'title' => 'Contact Details',
	'fields' => array (
		array (
			'key' => 'field_568062a79dc6c',
			'label' => 'Phone	Number',
			'name' => 'tw_phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '+1 (514) 555 9999',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5680634bcda10',
			'label' => 'Toll Free Phone',
			'name' => 'tw_toll_free_phone',
			'type' => 'text',
			'instructions' => 'Toll Free Phone Number',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '1-800 555 9999',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5680637fcda11',
			'label' => 'Fax',
			'name' => 'tw_fax',
			'type' => 'text',
			'instructions' => 'Fax Number',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '+1 (514) 555 8888',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568063aecda12',
			'label' => 'Email',
			'name' => 'tw_email',
			'type' => 'email',
			'instructions' => 'General Email address',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'name@company.com',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_568063d6cda13',
			'label' => 'Enable Number in Menu',
			'name' => 'tw_enable_phone_in_menu',
			'type' => 'true_false',
			'instructions' => 'Add a clickable phone number to your main menu',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Phone Number in Menu',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5680643779581',
			'label' => 'Phone Number in Menu',
			'name' => 'tw_phone_in_menu',
			'type' => 'select',
			'instructions' => 'Select which phone number to show in the main menu',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_568063d6cda13',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'phone' => 'Phone Number',
				'toll_free' => 'Toll Free Number',
			),
			'default_value' => array (
				'phone' => 'phone',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-contact-information',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'General contact information',
));

acf_add_local_field_group(array (
	'key' => 'tw_theme_address',
	'title' => 'Address',
	'fields' => array (
		array (
			'key' => 'field_5680666aabf21',
			'label' => 'Address 1',
			'name' => 'tw_address_1',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5680667babf22',
			'label' => 'Address 2',
			'name' => 'tw_address_2',
			'type' => 'text',
			'instructions' => 'Suite or Apartment Number',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56806692abf23',
			'label' => 'City',
			'name' => 'tw_city',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'City',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568066a8abf24',
			'label' => 'State/Province',
			'name' => 'tw_state',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'State or Province',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568066cfabf25',
			'label' => 'Zip or Post Code',
			'name' => 'tw_postcode',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Zip or Post Code',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568066ffabf26',
			'label' => 'Country',
			'name' => 'tw_country',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'choices' => $countries_array,
			'default_value' => array (
				'Canada' => 'Canada',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5680663287cbe',
			'label' => 'Enable Google Map',
			'name' => 'tw_enable_google_map',
			'type' => 'true_false',
			'instructions' => 'Check this box if you would like to enable a google map.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_568065cadb763',
			'label' => 'Google Map',
			'name' => 'tw_google_map',
			'type' => 'google_map',
			'instructions' => 'Search the Google Map for exact coordinates of your address',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5680663287cbe',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-contact-information',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

/****************************************************************
************** Social Networks **********************************
****************************************************************/
acf_add_local_field_group(array (
	'key' => 'tw_theme_social_networks',
	'title' => 'Social Networks',
	'fields' => array (
		array (
			'key' => 'field_568059c8f4e62',
			'label' => 'Facebook URL',
			'name' => 'tw_facebook_url',
			'type' => 'url',
			'instructions' => 'Facebook Fan Page, public profile or public group url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://facebook.com/USERNAME',
		),
		array (
			'key' => 'field_56805a1c2c7a0',
			'label' => 'Twitter @name',
			'name' => 'tw_twitter_handle',
			'type' => 'text',
			'instructions' => 'Twitter handle without the @ symbol',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'username',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56805a7a34e7e',
			'label' => 'Instagram @name',
			'name' => 'tw_instagram_handle',
			'type' => 'text',
			'instructions' => 'Instagram handle without the @ symbol',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'username',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56805a9234e7f',
			'label' => 'Pinterest URL',
			'name' => 'tw_pinterest_url',
			'type' => 'url',
			'instructions' => 'Pinterest board page url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://www.pinterest.com/USERNAME',
		),
		array (
			'key' => 'field_56805adc34e80',
			'label' => 'Tumblr URL',
			'name' => 'tw_tumblr_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://www.tumblr.com/USERNAME',
		),
		array (
			'key' => 'field_56805b0c34e81',
			'label' => 'Linkedin URL',
			'name' => 'tw_linkedin_url',
			'type' => 'url',
			'instructions' => 'LinkedIn Profile or company page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://www.linkedin.com/company/COMPANY-NAME',
		),
		array (
			'key' => 'field_56805b4834e82',
			'label' => 'Slideshare Page URL',
			'name' => 'tw_slideshare_url',
			'type' => 'url',
			'instructions' => 'Slideshare public page url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://www.slideshare.net/USERNAME',
		),
		array (
			'key' => 'field_56805baa9340d',
			'label' => 'Google+ Page URL',
			'name' => 'tw_googleplus_url',
			'type' => 'url',
			'instructions' => 'Google+ public profile or company page url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://plus.google.com/+COMPANY-NAME',
		),
		array (
			'key' => 'field_56805c7b9340e',
			'label' => 'Youtube Channel URL',
			'name' => 'tw_youtube_url',
			'type' => 'url',
			'instructions' => 'Youtube public channel url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://www.youtube.com/channel/USERNAME',
		),
		array (
			'key' => 'field_56805ccd9340f',
			'label' => 'Vimeo URL',
			'name' => 'tw_vimeo_url',
			'type' => 'url',
			'instructions' => 'Vimeo public profile or page url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://vimeo.com/USERNAME',
		),
		array (
			'key' => 'field_56815d1fdb225',
			'label' => 'RSS Feed',
			'name' => 'enable_rss_feed',
			'type' => 'true_false',
			'instructions' => 'Enable the RSS Feed icon in the social networks list',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable RSS Feed',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-social-information',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Social Networks URL\'s and Handles',
));

acf_add_local_field_group(array (
	'key' => 'tw_theme_facebook_settings',
	'title' => 'Facebook Settings',
	'fields' => array (
		array (
			'key' => 'field_56805fc5671b3',
			'label' => 'Facebook App',
			'name' => 'tw_enable_facebook_app',
			'type' => 'true_false',
			'instructions' => 'Enable "Facebook App" to allow for Facebook commenting and API integration',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Facebook App',
			'default_value' => 0,
		),
		array (
			'key' => 'field_568060512e572',
			'label' => 'Facebook App ID',
			'name' => 'tw_facebook_app_id',
			'type' => 'text',
			'instructions' => 'Add your Facebook App ID. If you do not have one, you can <a href="https://developers.facebook.com" target="_blank">create an app here</a>',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56805fc5671b3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568060f62e573',
			'label' => 'Blog Commenting',
			'name' => 'tw_commenting_options',
			'type' => 'radio',
			'instructions' => 'Choose the type of commenting you would like.
Facebook comments needs to have a valid Facebook App ID. ',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56805fc5671b3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'wp_comments' => 'Wordpress Comments Only',
				'fb_comments' => 'Facebook Comments Only',
				'wp_fb_comments' => 'Wordpress and Facebook Comments',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-social-information',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Facebook App Integration Settings',
));



acf_add_local_field_group(array (
	'key' => 'tw_theme_twitter_settings',
	'title' => 'Twitter API Settings',
	'fields' => array (
		array (
			'key' => 'field_5682f87bca232',
			'label' => 'Twitter API',
			'name' => 'tw_enable_twitter_api',
			'type' => 'true_false',
			'instructions' => 'Choose this if you have a Twitter account and want to display a Twitter feed widget in the site sidebars,',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Twitter API',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5682f77980191',
			'label' => 'Access Token',
			'name' => 'tw_twitter_access_token',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5682f87bca232',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5682f7e180192',
			'label' => 'Access Token Secret',
			'name' => 'tw_twitter_access_token_secret',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5682f87bca232',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5682f7f580193',
			'label' => 'Consumer Key',
			'name' => 'tw_twitter_consumer_key',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5682f87bca232',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5682f80580194',
			'label' => 'Consumer Secret',
			'name' => 'tw_twitter_consumer_secret',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5682f87bca232',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-social-information',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Twitter API',
));

/****************************************************************
************** Advanced ******************************************
****************************************************************/


acf_add_local_field_group(array (
	'key' => 'tw_theme_404_settings',
	'title' => '404 Page',
	'fields' => array (
		array (
			'key' => 'field_5682fa4f33161',
			'label' => 'Title',
			'name' => 'tw_theme_404_title',
			'type' => 'text',
			'instructions' => 'Enter the 404 Page title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Page Not Found',
			'placeholder' => 'Page Not Found',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5682fababacc2',
			'label' => 'Content',
			'name' => 'tw_theme_404_content',
			'type' => 'wysiwyg',
			'instructions' => 'Enter 404 Page body content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'We couldn\'t find the page what you were looking for!
Try a search to find what you were looking for!',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_5682fa8033162',
			'label' => 'Image',
			'name' => 'tw_theme_404_img',
			'type' => 'image',
			'instructions' => 'Choose a background image.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5682fcc51f173',
			'label' => 'Search Bar',
			'name' => 'tw_theme_404_enable_search_bar',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Search Bar',
			'default_value' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-advanced',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'tw_theme_prefetch_dns_settings',
	'title' => 'DNS Prefetch',
	'fields' => array (
		array (
			'key' => 'field_5682fb55a3365',
			'label' => 'Google Fonts',
			'name' => 'tw_theme_prefetch_google_fonts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Google Fonts Prefetching',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5682fb7ba3366',
			'label' => 'Google Analytics',
			'name' => 'tw_theme_prefetch_google_analytics',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Google Analytics Prefetching',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5682fb8aa3367',
			'label' => 'Google Tag Manager',
			'name' => 'tw_theme_prefetch_google_tagmanager',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Google Tag Manager Prefetching',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5682fb8aa3890',
			'label' => 'Google Maps',
			'name' => 'tw_theme_prefetch_google_maps',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Google Maps Prefetching',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5682fb9fa3368',
			'label' => 'Facebook',
			'name' => 'tw_theme_prefetch_facebook',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Facebook Prefetching',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-advanced',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));


acf_add_local_field_group(array (
	'key' => 'tw_theme_default_img_settings',
	'title' => 'Default Image',
	'fields' => array (
		array (
			'key' => 'field_56882a429c71d',
			'label' => 'Default Image',
			'name' => 'tw_theme_default_img',
			'type' => 'image',
			'instructions' => 'Choose a default image for use across the site when an image link is broken or not available.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-advanced',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Default Image',
));

endif;